title = "William Vigolo da Silva"
description = """
Personal website and blog of William Vigolo da Silva, a software developer
"""
base_url = "https://williamvds.me"
compile_sass = true
highlight_code = true
highlight_theme = "kronuz"
build_search_index = false
generate_rss = true

[extra]
headline = "Software developer"
username = "williamvds"
address  = ""
email    = "william@williamvds.me"
repo     = "https://github.com/williamvds"
dateFmt  = "%d %B %Y"

[extra.contacts.email]
url   = "mailto:"
value = "william@williamvds.me"

[extra.contacts.phone]
url       = "tel:"
value     = ""
printOnly = true

[extra.contacts.web]
url       = "https://"
value     = "williamvds.me"
printOnly = true

[extra.accounts.linkedin]
name = "LinkedIn"
url  = "https://linkedin.com/in/"
icon = "linkedin-box"

[extra.accounts.github]
name = "GitHub"
url  = "https://github.com/"
icon = "github-circle"

[[extra.links]]
name = "Home"
url  = "/"
icon = "home"

[[extra.links]]
name = "Résumé"
url  = "/cv"
icon = "file-document"

[[extra.links]]
name = "Blog"
url  = "/blog"
icon = "typewriter"

[[extra.links]]
name = "RSS feed"
url  = "/rss.xml"
icon = "rss-box"

[[extra.links]]
name = "PGP key"
url  = "/pgp.pub"
icon = "key"
